# Generated by Django 4.2.27 on 2025-12-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio_o_ip', models.CharField(max_length=255, unique=True, verbose_name='Dominio o IP')),
                ('usuario_servidor', models.CharField(max_length=100, verbose_name='Usuario del Servidor')),
                ('contrasena_bot', models.CharField(max_length=255, verbose_name='Contraseña del Bot')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
    ]
