# Generated by Django 6.0 on 2026-01-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado del servidor')),
                ('archivo', models.CharField(max_length=50, verbose_name='Nombre del archivo o directorio')),
                ('fecha', models.DateField()),
                ('idServer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.server')),
            ],
        ),
    ]
