# Generated by Django 6.0 on 2026-01-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio_origen', models.CharField(max_length=255, verbose_name='Directorio a respaldar (Origen)')),
                ('directorio_destino', models.CharField(max_length=255, verbose_name='Directorio donde guardar (Destino)')),
                ('frecuencia_cron', models.CharField(help_text='Formato: min hora dia mes dia_semana (ej: 0 3 * * *)', max_length=100, verbose_name='Frecuencia (Cron)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servidor_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldos_destino', to='core.server', verbose_name='Servidor Destino')),
                ('servidor_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldos_origen', to='core.server', verbose_name='Servidor Origen')),
            ],
            options={
                'verbose_name': 'Configuración de Respaldo',
                'verbose_name_plural': 'Configuraciones de Respaldo',
            },
        ),
    ]
