# Generated by Django 5.1.15 on 2026-01-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionrespaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionrespaldo',
            name='dst_user',
            field=models.CharField(default=1, max_length=50, verbose_name='Usuario destino'),
            preserve_default=False,
        ),
    ]
